creativecommons/cc-resource-archive

Dockerfile, docker-compose.yml, docs/Gemfile.lock
Use custom ruby docker instead of custom jekyll docker
- Unfortunately, the official jekyll docker images are out of date and contain errors: https://hub.docker.com/u/jekyll
- Also see: https://github.com/envygeeks/jekyll-docker/issues
- The custom Dockerfile was created based, in part, on: https://github.com/BretFisher/jekyll-serve/issues/82#issuecomment-1397827960 (Thank you!)
On my laptop, this new configuration is significantly faster.
index.md`).
<details>
<summary>Developer Certificate of …
=> Use custom ruby docker instead of custom jekyll docker

README.md
Fixes grammatical errors in the Readme.md file.
Fixes #67  by @Lakshay-Pruthi
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution …
```
=> Fixed grammatical errors in Readme

docs/style.css
Fixes #71  by @justaskulkarni 
Removal of unused greenbanner CSS selector.
The only search result corresponding to the id greenbanner is in the style.css file.
There is no HTML div with id greenbanner corresponding to it.
Therefore, the following piece of code is redundant:
To add to my point:
Here, the image is as shown in the picture below:
Therefore, the green color of the CC logo comes from the image itself and has no relation with the greenbanner selector.
index.md`).
<details> …
=> Removal of Redundant CSS

docs/_data/languages.yml, docs/all.html, docs/index.html
Fixes #87 by @Javali-M
To increase user experience, the language abbreviations have been expanded to display all the names clearly in a bulleted format in two columns.
Formatted the names into an unordered list and set the columns attribute to 2 to display them side by side.
index.md`).
<details>
```
Version 1.1
Suite D4700
San …
```
=> Expanded the abbreviations of languages

docs/_layouts/resource.html, docs/cash-music-creative-commons-portal.html, docs/cc-licenses-poster.html, docs/creative-commons-kiwi.md, docs/creative-commons-licenses-for-nonprofit-organizations.html, docs/get-cc-savvy.html, docs/guide-to-using-public-domain-tools.html, docs/oer-whats-in-it-for-me.md, docs/six-licenses-for-sharing-your-work.html, docs/wanna-work-together.html
Fixes #11  by @[Keerthivardhan]
This PR fixes all the broken links present in https://resources.creativecommons.org/
This pull request fixes all the broken links in the website. I've tested all the links and ensured that they work correctly now.
I was able to identify a few broken links on the website through exploration and assistance from the brokenlinkchecker.com tool. To locate functional versions of these links, I utilized the internet archives.
404 error is fixed.
similarly, some other links are:
index.md`).
For the purposes of this DCO, "license" is equivalent to "license or public domain dedication," and "open source license" is equivalent to "open content license or public …
=> Fixing broken links

docs/submission.html
Fixes #93 by @itsyuxuan
I replace the expired Google Form link with the project GitHub link to encourage pull requests, according to the will of the original developer.
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, but …
```
=> Remove expired form, encourage pull request

docs/_layouts/listing.html
Fixes #105 by @xaid-vfx
Two functions (`UpdateQueryString()` and `RemoveQueryString()`) that were not functional are removed from listing.html 
Tested the functionality of the website locally and it works fine. To test it on your end, apply and remove different filters to see results.
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Remove unnecessary Js functions

docs/_layouts/listing.html, docs/_layouts/resource.html, docs/submission.html
Fixes #124  by @JennySimen
This PR adds the meta tag at the top of the HTML document to specify viewport setting. This is to make sure the site displays well on all devices and to make the web pages to follow the best practices and improve SEO.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Added meta tag to the top of HTML document

docs/_layouts/resource.html
Fixes #111  by @C-NikhilKarthik
Fixed the anchor tag that was not closed , along with the wrong h3 closing a h2 tag.
I have fixed the resource.html file in _layout folder that had the following issue :
1. Anchor tag enclosing the Title of the page was not enclosed
2. The h2 that was wrapping the above mentioned Anchor tag was incorrectly enclosed using a h3 tag.
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, …
```
=> fix: fixed missing anchor tag in resource.html

docs/style.css
Fixes #137 by @harshhh11
This PR updates `style.css` to use margin-shorthand property instead of specific margin properties like `margin-left`, `margin-right`,etc to remove redundancy
index.md`).
<details>
```
Version 1.1
Suite D4700
license …
```
=> Updated style.css to use margin-shorthand to remove redundancy

docs/_layouts/listing.html, docs/_layouts/resource.html, docs/submission.html
Fixes #128  by @JennySimen
This PR adds the HTML lang attribute at the top of the HTML document which is neccessary because it helps search engines to return language-specific results on the SERP and improves the accessibility of the website.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Added the HTML lang attribute to the HTML documents

docs/Gemfile.lock, docs/_layouts/listing.html, docs/style.css
Fixes #175 by @sj-jain
Not clickable full part of `listing.html` card. 
The whole card is now clickable. 
https://github.com/creativecommons/cc-resource-archive/assets/93199036/30444e87-fdad-4aec-85da-1751451c8a9d
<details>
```
Version 1.1
Suite D4700
By …
```
=> Add changes to listing.html make it clickable

docs/creative-commons-kiwi.md
Fixes #155 by @justaskulkarni 
Before this PR, there was a yaml exception in the terminal because the link in creative-commons-kiwi.md was spanned across 2 lines. Yaml is whitespace sensitive, and hence YAML expects key-value pairs to be defined on a single line, so it interprets the second line as an exception. 
Removed whitespace and fixed the link.
Before - 
After - 
index.md`).
<details>
```
Version 1.1
Copyright …
```
=> Fixed yaml exception in creative-commons-kiwi.md

docs/_layouts/listing.html
Fixes #170 by @Xaid-vfx
Removing the unnecessary liquid if conditions in listing.html
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> remove liquid if conditions

docs/style.css
Related to #26  by @tinniaru3005
Adds responsiveness to the resource-navbar section, which makes the whole page responsive and solves footer misalignment automatically.
Changed the `style.css` file, added `display: flex` property.
Before: 
After:
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is …
```
=> Made resource-navbar section responsive

docs/style.css
Fixes #62 by @Aaishpra
reduced the download button size
changes made on style.ss file
1. Visit homepage of creative commons.
2. Find the resource list.
3. Click on any of the resources.
4. Check the view in detail button size.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and …
```
=> #62 Reduced the download button size

docker-compose.yml
- Fixes #265  by @Murdock9803 
Updates to the current spec by removing the `version` element from `docker-compose.yml` file.
* removed the `version` element.
* updated the documentation URL to https://docs.docker.com/compose/compose-file/
* https://docs.docker.com/compose/compose-file/04-version-and-name/#version-top-level-element-obsolete
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Updated to the current spec in docker-compose.yml 

docs/_layouts/resource.html, docs/submission.html
- Fixes #285 by @Murdock9803
The pull request removes the google analytics function code from the [resource.html](https://github.com/creativecommons/cc-resource-archive/blob/main/docs/_layouts/resource.html) and the [submission.html](https://github.com/creativecommons/cc-resource-archive/blob/main/docs/submission.html) files. The functionality can be re-implemented later with proper discussion.
index.md`).
<details>
```
Developer Certificate of …
```
=> removed the google analytics function from resource.html and submission.html

docs/_assets/css/style.css
- Fixes #288 by @Murdock9803
The pull request aims at organising the `style.css` file with separating mixed code for different html pages in suitable sections.
furthermore, the css selectors for the same html page are grouped together. Also, Documentation is provided for better and quick understanding of the file.
Also, the code is formatted using `prettier code formatter`.
index.md`).
<details>
```
Version 1.1 …
```
=> Organised the code in style.css with documentation and segregation

docs/_resources/guide-to-using-public-domain-tools.html, docs/_resources/six-licenses-for-sharing-your-work.html
- Fixes #290 by @Murdock9803
The pull request aims at updating the links or paths to some downloadable resources which are present at the bottom of some resource pages, as shown in the accompanying picture.
The addition of `_assets` directory to the codebase required the updation of paths which pointed towards the downloadable resources.
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux …
```
=> Updates the paths to downloadable PDFs and resources from resource pages.

resourcetemplate.md
- Fixes #293  by @Murdock9803 
After the merging of PR #289, the path to `images` folder changed in the codebase. So this PR updates these paths in the `resourcetemplate.md` file.
Changed the paths from `/images` to `/_assets/images`
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to …
```
=> Updated the resource template with new paths for images

docs/_assets/css/style.css, docs/_layouts/listing.html
- Fixes #301 by @Murdock9803 
- Fixes #165 by @KrownWealth
- Related to #101 by @Xaid-vfx 
The pull request aims at enhancing the `listing.html` file by providing proper documentation, formatting the code and also a heading for the page.
The PR performs the following tasks:
- Adds a heading to the page.
- Adds clear documentation about various sections in the file.
- Formats the code with `prettier` code formatter.
Heading:
index.md`).
<details>
``` …
```
=> Refactors the listing.html file and adds a heading to the page

docs/_pages/submission.html
- Fixes #318  by @mahak-juriani
On submission page - opens github links in new page, spell fix
https://github.com/user-attachments/assets/324fb542-cef4-4647-95e7-4293804fd43a
index.md`).
<details>
```
Version 1.1
Suite D4700
license document, …
```
=> Submit page - external links open in new page, +spelling update

resourcetemplate.md
- Fixes #299 by @Murdock9803
In the resourcetemplate.md file, there is a description about available options to choose from, for the medium of resource. But there were total 5 options documented. This pull request ensures that the sixth option is present as well.
index.md`).
<details>
Version 1.1
Suite D4700 …
=> Fixes #299 Add "Infographic" to the documentation about media in resourcetemplate.md

docs/_includes/header.html
- Fixes #338 by @SumaiyaaRq
This PR adds missing anchor text for search portal url in the explore-menu.
1.Go to cc-resource-archive page.
2.Click on Explore CC .
3.Check the explore-menu.
4.See correction.
index.md`).
<details>
```
Version 1.1
Suite D4700
Everyone is permitted to copy and distribute verbatim …
```
=> BugFix: Added anchor-text for Search Portal URL in explore-menu.

docs/_assets/css/style.css
- Fixes #340  by @SisiVero
This PR addresses the issue of the identity logo not being aligned in accordance to the design system
The identity logo has been left aligned in accordance to the design system. The style line removed did not affect other h1 texts. 
index.md`).
<details>
```
Version 1.1
Suite D4700 …
```
=> Identity Logo Left Aligned In Accordance To  design System

docs/_pages/all.html
- Fixes #344 by @SisiVero 
This pull request adds the clickable labels for each checkbox element in the topic list of the `resourcenav` component. By associating each checkbox with a unique `id` and using the `for` attribute on its `label`, users can now select checkboxes by clicking on the label tex.
To implement this feature, unique `id` attributes were added to each checkbox. Each label is now associated with its checkbox by referencing this `id` with the `for1 attribute. This approach allows users to toggle checkbox by clicking the label text.
To verify:
-Navigate to `See all resources`
-Click on each label text to confirm that the associated checkbox is toggled accordingly.
index.md`).
[best_practices]:https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f …
=> Label Check Feature Added to `all.html` Inputs and Associated Labels

docs/_includes/footer.html
- Fixes #355  by @SumaiyaaRq 
This PR removes the publicly posted telephone number from the footer region in this project as all legitimate contacts have alternative ways to reach .
The telephone number has been removed from `footer.html` in `docs/_includes`. 
1. Open the Website .
2. Navigate to the Footer region .
3. See changes 
index.md`).
<details>
```
Version 1.1
Copyright (C) 2004, 2006 The Linux Foundation and …
```
=> Feature : Removed Telephone Number from Footer

docs/_includes/header.html
- Fixes #361 by @Queen-codes 
this pr removes global summit option from the explore menu
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a …
```
=> removed global summit from explore menu

docs/_includes/footer.html
- Fixes #363 by @Queen-codes 
index.md`).
<details>
```
Version 1.1
Suite D4700
By making a contribution to this project, I certify that:
(a) The …
```
=> update footer to reflect upstream changes
